### ISSUE TITLE
full images

### ISSUE THREAD

**Issue by K1ngOfCurses** [hassan-sd/tiktok-face-scraper#1]
is there a way we can get frames the full size instead of it being resized smaller, and also is there a way we can input our own videos for it to be extracted

**Comment by hassan-sd** [comment]
It's not resizing the videos in the script, maybe the download is.

In regards to adding local videos, yes I've pushed a new commit so you can pull in a directory containing 1 or more videos and it will perform extraction for  frames and faces

https://github.com/hassan-sd/tiktok-face-scraper/commit/3654a7f29452e442a4411669e60d6d6c408339b4
